name: RELEASE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Release
        uses: parkside-securities/gitops-actions@0.3.14
        with:
          cmd: release_master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
